
type "F:\FOLDERS\Work\Contracts\Singular\billed\Mandat 3\punch_mandat_3.txt"
type "F:\FOLDERS\Work\Contracts\Singular\billed\Mandats 1 et 2\punch_mandats_1_2.txt"
type "F:\FOLDERS\Work\Contracts\Lyo-Sublima\punch.txt"
type "F:\FOLDERS\Work\Contracts\Lyo-Sublima\cons.txt"
type "F:\FOLDERS\Work\Contracts\Lyo-Sublima\invoices\2022-10-001\cons.txt"
type "F:\FOLDERS\Work\Contracts\Lyo-Sublima\invoices\2022-10-001\punch.txt"
type "F:\FOLDERS\Work\Contracts\Sino\punch.txt"

type "F:\FOLDERS\Work\Contracts\Singular\billed\Mandat 3\punch_mandat_3_v2.txt"
type "F:\FOLDERS\Work\Contracts\Singular\billed\Mandats 1 et 2\punch_mandats_1_2_v2.txt"
type "F:\FOLDERS\Work\Contracts\Lyo-Sublima\punch_v2.txt"
type "F:\FOLDERS\Work\Contracts\Lyo-Sublima\cons_v2.txt"
type "F:\FOLDERS\Work\Contracts\Lyo-Sublima\invoices\2022-10-001\cons_v2.txt"
type "F:\FOLDERS\Work\Contracts\Lyo-Sublima\invoices\2022-10-001\punch_v2.txt"
type "F:\FOLDERS\Work\Contracts\Sino\punch_v2.txt"
